version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: chore
      include: scope
    groups:
      root-production-minor-patch:
        applies-to: version-updates
        dependency-type: production
        update-types:
          - minor
          - patch
        patterns:
          - "*"
      root-development-minor-patch:
        applies-to: version-updates
        dependency-type: development
        update-types:
          - minor
          - patch
        patterns:
          - "*"
      root-security-updates:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "10:00"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - area:ci
    commit-message:
      prefix: chore
      include: scope
    groups:
      github-actions-minor-patch:
        applies-to: version-updates
        update-types:
          - minor
          - patch
        patterns:
          - "*"
      github-actions-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
